import AppKit
import ArgumentParser
import Foundation

@main
struct CodeReset: ParsableCommand {
    @Flag(name: [.long, .customShort("A")])
    var keepArgvJSON = false

    @Flag(name: [.long, .customShort("E")])
    var keepExtensions = false

    @Flag(name: [.long, .customShort("L")])
    var keepLanguagepacksJSON = false

    @Flag(name: [.long, .customShort("S")])
    var keepSettingsJSON = false

    @Flag(name: [.long, .customShort("P")])
    var deployConfigurationProfile = false

    func run() throws {
        let applicationsURL = try FileManager.default.url(
            for: .applicationDirectory, in: .userDomainMask, appropriateFor: nil, create: true)

        let codeDataURL = applicationsURL.appending(component: "code-portable-data")

        let tempDataURL = FileManager.default.temporaryDirectory.appending(
            component: UUID().uuidString)

        try FileManager.default.createDirectory(at: codeDataURL, withIntermediateDirectories: true)

        try FileManager.default.createDirectory(at: tempDataURL, withIntermediateDirectories: true)

        defer {
            try? FileManager.default.removeItem(at: tempDataURL)
        }

        if keepArgvJSON {
            try copyItem(at: codeDataURL, to: tempDataURL, path: "argv.json")
        }

        if keepExtensions {
            try copyItem(at: codeDataURL, to: tempDataURL, path: "extensions")
        }

        if keepLanguagepacksJSON {
            try copyItem(at: codeDataURL, to: tempDataURL, path: "user-data/languagepacks.json")
        }

        if keepSettingsJSON {
            try copyItem(at: codeDataURL, to: tempDataURL, path: "user-data/User/settings.json")
        }

        _ = try FileManager.default.replaceItemAt(codeDataURL, withItemAt: tempDataURL)

        if deployConfigurationProfile {
            let profileURL = try createProfile()
            NSWorkspace.shared.open(profileURL)
        }
    }
}

func copyItem(at srcURL: URL, to dstURL: URL, path: some StringProtocol) throws {
    let srcURL = srcURL.appending(path: path)
    let dstURL = dstURL.appending(path: path)

    try FileManager.default.createDirectory(
        at: dstURL.deletingLastPathComponent(), withIntermediateDirectories: true)

    try FileManager.default.copyItem(at: srcURL, to: dstURL)
}

struct CodeProfile: Codable {
    var PayloadContent: [CodeProfilePayload]
    var PayloadDescription: String
    var PayloadDisplayName: String
    var PayloadIdentifier: String
    var PayloadUUID: String
    var PayloadType: String
    var PayloadVersion: Int
}

struct CodeProfilePayload: Codable {
    var PayloadType: String
    var PayloadVersion: Int
    var PayloadIdentifier: String
    var PayloadUUID: String
    var PayloadDisplayName: String
    var AllowedExtensions: String
    var ExtensionsAutoUpdate: String
    var EnableFeedback: Bool
    var TelemetryLevel: String
    var UpdateMode: String
}

func createProfile() throws -> URL {
    let uuid = UUID()

    let profilePayload = CodeProfilePayload(
        PayloadType: "com.microsoft.VSCode",
        PayloadVersion: 1,
        PayloadIdentifier: "com.microsoft.VSCode.\(uuid.uuidString)",
        PayloadUUID: uuid.uuidString,
        PayloadDisplayName: "Visual Studio Code",
        AllowedExtensions: String(
            data: Data(PackageResources.extensions_allowed_json), encoding: .utf8)!,
        ExtensionsAutoUpdate: "off",
        EnableFeedback: false,
        TelemetryLevel: "off",
        UpdateMode: "manual",
    )

    let profile = CodeProfile(
        PayloadContent: [profilePayload],
        PayloadDescription: "This profile manages Visual Studio Code. Generated by CodeReset.",
        PayloadDisplayName: "Visual Studio Code",
        PayloadIdentifier: "com.microsoft.VSCode",
        PayloadUUID: UUID().uuidString,
        PayloadType: "Configuration",
        PayloadVersion: 1,
    )

    let profileURL = FileManager.default.temporaryDirectory.appending(
        component: "com.microsoft.VSCode.mobileconfig")

    try PropertyListEncoder().encode(profile).write(to: profileURL)

    return profileURL
}
